# Generated by Django 5.1.4 on 2025-08-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaintactivity_complaintattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('network_slow', 'Network Slow'), ('network_down', 'Network Down'), ('wifi_issues', 'WiFi Issues'), ('server_issues', 'Server Issues'), ('email_issues', 'Email Issues'), ('internet', 'Internet Connectivity'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
